name: CDLP FrontEnd CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2


    - name: Use Node.js ${{ matrix.node-version }}
      
      uses: c-hive/gha-yarn-cache@v2
      


    - name: Setup Code Climate test-reporter
      run: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

    
    - name: Install dependencies
      run: yarn install
      working-directory: src


    - name: Run the tests and generate coverage report
      run: |
            ./cc-test-reporter before-build
            yarn test ./src --coverage
      working-directory: src


    - name: Build
      run: yarn run build
      working-directory: src


    - name: Print Success Message for CD finish
      run : echo "CD Pipeline part Finished successfully!"

    
  